# Generated by Django 3.0.7 on 2020-06-10 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managem_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='name',
            new_name='subscription',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='subscribe',
            new_name='category',
        ),
    ]
