# Generated by Django 3.0.7 on 2020-06-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managem_app', '0003_remove_history_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='due_date',
            field=models.DateField(),
        ),
    ]
