# Generated by Django 3.0.7 on 2020-06-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managem_app', '0004_auto_20200610_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='due_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
